//import "../styles/globals.css";
//import Header from "@/components/Header";
//import Providers from "./Providers";
//import Navbar from "@/components/Navbar";
//import SearchBox from "@/components/SearchBox";

import Header from "./Header";
import Navbar from "./Navbar";
import Providers from "./Providers";
import Footer from "./Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Providers>
          {/*header*/}
          <Header />
          {/*navbar*/}
          <Navbar />
          {children}
          {/*footer*/}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
